### PR TITLE
added basic flex properties

### PR DESCRIPTION
**Pull request by philipyoungg**
added 
- flex-nowrap, 
- flex-grow-0, 
- flex-grow-1, 
- flex-shrink-0,
- flex-shrink-1

reason to merge: These properties needed for basic flexbox layout manipulation.

### CODE REVIEW

**Comment by ixley** [comment]
@philipyoungg Consider that `nowrap` is the default value for `flex-wrap`. It seems less useful to include that than `flex-wrap: wrap;`.

Also, while I acknowledge there isn't the same granular control, you can still accomplish most layout manipulation (of `flex-grow` and `flex-shrink`) with `.flex-auto` and `.flex-none`.

**Comment by philipyoungg** [comment]
@ixley consider this scenario. 

On desktop breakpoint, I use `flex-direction: row` and `flex-wrap: wrap` to have a row with three column in the same width.

On the phone, I want to change the layout to `flex-direction: column` and `flex-wrap: nowrap` to make sure all the children element behaves like display block.

Of couse we can achieve the same thing by using float, but there's thing that display table / float can't do (like order) and easier vertical spacing.

Regarding `flex-auto` there's a bug on older browser (either IE9 or Android below Jelly Bean) that ignore this value.

Instead of `flex-auto: 1 100px`
Solution: use `flex-grow: 1; min-width:100px; width: 100%` 

While on the same topic, `flex-flow: row nowrap` didn't works on older browser too—even with auto prefixer. 

What works is using `flex-direction: row; flex-wrap: nowrap`

**Comment by kelkes** [comment]
Any reason not to merge this PR? Need any help with this repo?

**Comment by philipyoungg** [comment]
@kelkes as far as I know, @mrmrs prefers using table for layout instead of flexbox. That's one reason this PR haven't merged yet.

**Comment by abradley2** [comment]
I don't think the vendor prefixes are necessary here, since the tachyons-cli uses [the build-css](https://github.com/tachyons-css/tachyons-build-css) module to add in the vendor prefixes.

Very much would like to see these flex-box attributes added. Or if the motivation is that there's a simpler way, perhaps have a section on flex added to the documentation?

**Comment by Jayphen** [comment]
What's going on with this PR? I'm patching this in locally but would nice to see full support for flex. Is Tachyons still actively developed?

Edit: I see that the changes are included [in the main repo](https://github.com/tachyons-css/tachyons/blob/master/src/_flexbox.css) – I'm a little confused as to why this repo would not be matching?

**Comment by johno** [comment]
@philipyoungg thank you so much for this pr! Somehow this got buried in my GitHub notifications. This is now all supported. We will be making a handful of further flexbox changes this week as well.

@Jayphen Tachyons is still actively developed, just sometimes the individual modules fall out of date 😞. For Tachyons v5 we will be moving to a monorepo so that we can automate keeping the individual modules up to date.

**Pull request closed without merging**
